apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: kubevirtbmc-metrics-certs
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - SERVICE_NAME.SERVICE_NAMESPACE.svc
  - SERVICE_NAME.SERVICE_NAMESPACE.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kubevirtbmc-selfsigned-issuer
  secretName: metrics-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: kubevirtbmc-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - kubevirtbmc-webhook-service.{{ .Release.Namespace }}.svc
  - kubevirtbmc-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kubevirtbmc-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: kubevirtbmc-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
