{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: kubevirtbmc-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: virtbmc-rbac
    app.kubernetes.io/created-by: kubevirtbmc
    app.kubernetes.io/instance: virtbmc-sa
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: kubevirtbmc
  name: kubevirtbmc-virtbmc
  namespace: {{ .Release.Namespace }}
{{- end }}
