apiVersion: virtualmachine.kubevirt.io/v1alpha1
kind: VirtualMachineBMC
metadata:
  labels:
    app.kubernetes.io/name: virtualmachinebmc
    app.kubernetes.io/instance: virtualmachinebmc-sample
    app.kubernetes.io/part-of: kubevirtbmc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubevirtbmc
  name: virtualmachinebmc-sample
  namespace: kubevirtbmc-system
spec:
  # Reference to the Secret containing the credentials
  authSecret:
    namespace: kubevirtbmc-system
    name: bmc-cred

  # The VirtualMachine this BMC manages
  virtualMachine:
    namespace: default
    name: test-vm
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-cred
  namespace: kubevirtbmc-system
type: Opaque
data:
  username: YWRtaW4=  
  password: cGFzc3dvcmQ= 